### ISSUE TITLE
LOFAR_ddfacet pipeline has no matching parset

### ISSUE THREAD

**Issue by mknapp55** [revoltek/LiLF#31]
When running the LOFAR_ddfacet.py pipeline, I got the following error: 
```
Singularity> python3 /home/mknapp/software/LiLF/pipelines/LOFAR_ddfacet.py
2023-11-26 10:47:29 - INFO - Logging initialised in /Download/mss/id693094_-_v830tau (file: pipeline-ddfacet.logger_2023-11-26_10:47:29.logger)
2023-11-26 10:47:29 - WARNING - Hostname GALATEA unknown.
2023-11-26 10:47:29 - INFO - Scheduler initialised for cluster Unknown: GALATEA (maxThreads: 12, qsub (multinode): False, max_processors: 12).
Traceback (most recent call last):
  File "/home/mknapp/software/LiLF/pipelines/LOFAR_ddfacet.py", line 19, in <module>
    parset_dir = parset.get('LOFAR_ddfacet','parset_dir')
  File "/usr/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'LOFAR_ddfacet'
```
I checked the parset directory and indeed there are no parsets for LOFAR_ddfacet.  Is this pipeline deprecated?  Should I be using pipeline LOFAR_dd.py instead?

**Comment by revoltek** [comment]
please use LOFAR_dd pipeline, the LOFAR_ddfacet was made for a test
