### ISSUE TITLE
memory error while running a deep field

### ISSUE THREAD

**Issue by botteon** [revoltek/LiLF#9]
Hi, I'm getting the following error running `LOFAR_dd-serial.py` on a deep (72h) observation:

```
 - 15:50:29 - ClassJones         | Build solution Dico for killMS
 - 15:50:29 - ClassJones         |   Parsing solutions ddcal/c00/solutions/interp.h5:sol000/phase000+amplitude000
 - 15:50:29 - ClassJones         | Parsing h5file pattern ddcal/c00/solutions/interp.h5
 - 15:50:29 - ClassJones         |   Applying ddcal/c00/solutions/interp.h5 solset ['sol000'] soltabs {'tec000': False, 'phase000': True, 'amplitude000': True}
 - 15:55:01 - AsyncProcessPool   | process io00: exception raised processing job DATA:0:0: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/DDFacet/Other/AsyncProcessPool.py", line 870, in _dispatch_job
    result = call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/DDFacet/Data/ClassVisServer.py", line 545, in _handler_LoadVisChunk
    JonesMachine.InitDDESols(DATA)
  File "/usr/local/lib/python3.8/dist-packages/DDFacet/Data/ClassJones.py", line 170, in InitDDESols
    DicoSols, TimeMapping, DicoClusterDirs = self.MakeSols("killMS", DATA, quiet=quiet)
  File "/usr/local/lib/python3.8/dist-packages/DDFacet/Data/ClassJones.py", line 299, in MakeSols
    DicoClusterDirs_killMS, DicoSols = self.GiveKillMSSols()
  File "/usr/local/lib/python3.8/dist-packages/DDFacet/Data/ClassJones.py", line 459, in GiveKillMSSols
    DicoClusterDirs, DicoSols, VisToJonesChanMapping = self.GiveKillMSSols_SingleFile(
  File "/usr/local/lib/python3.8/dist-packages/DDFacet/Data/ClassJones.py", line 794, in GiveKillMSSols_SingleFile
    VisToJonesChanMapping,DicoClusterDirs,DicoSols,G=self.ReadH5(SolsFile)
  File "/usr/local/lib/python3.8/dist-packages/DDFacet/Data/ClassJones.py", line 671, in ReadH5
    solset_gains.append(np.exp(1j * phase))
MemoryError: Unable to allocate array with shape (15304, 29, 35, 768, 2) and data type complex128
```

The guess of Reinout is that all solutions in all ms files are stored in a single H5 file with a giant time axis (15304). Could this be the issue?
The pipeline runs fine on the same node for a shorter (4h) observation.

ps: I had to add `--Misc-ConserveMemory=1` to the DDF call otherwise I was getting another kind of error (AsyncProcessPool   | worker 'compXX' killed by signal SIGKILL), but this should not be related to LiLF but to DDF..

**Comment by revoltek** [comment]
This problem was solved with a patch of Henrik in DDF, but this is only in the DDF version of the latest singularity

**Comment by botteon** [comment]
Thank you, indeed it passed the critical point using the latest singularity :)
